# Generated by Django 3.0.8 on 2020-10-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('was_born', models.DateField(blank=True, null=True, verbose_name='Родился в')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='finished_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда закончили читать'),
        ),
        migrations.AddField(
            model_name='book',
            name='started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда начали читать'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Author'),
        ),
    ]
