# Generated by Django 3.0.8 on 2020-10-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201011_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='was_born',
            field=models.DateField(blank=True, help_text='Год-Месяц-День', null=True, verbose_name='Родился в'),
        ),
        migrations.AlterField(
            model_name='book',
            name='finished_date',
            field=models.DateField(blank=True, help_text='Год-Месяц-День', null=True, verbose_name='Когда закончили читать'),
        ),
        migrations.AlterField(
            model_name='book',
            name='started_date',
            field=models.DateField(blank=True, help_text='Год-Месяц-День', null=True, verbose_name='Когда начали читать'),
        ),
    ]
