# Generated by Django 3.0.8 on 2020-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201011_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(null=True, verbose_name='Какое послевкусие от книги?'),
        ),
    ]
